# pull the base image
FROM node:lts-alpine3.14

# set the working directory
WORKDIR /api

# install app dependencies
COPY ./api/package.json ./

COPY ./api/package-lock.json ./

RUN npm install

# copy app

COPY ./api ./

# start app

CMD ["node", "server.js"]