version: "3.8"
services:
 mysql:
  image: mysql
  ports:
   - 3306:3306
  volumes:
   - db_data:/var/lib/mysql
  env_file:
   - .env

 adminer:
  image: adminer
  ports:
   - 8080:8080

 demo-api:
  image: demo-api:0.50
  ports:
   - 4000:4000
  env_file:
   - .env

 demo-app:
  image: demo-app:0.50
  ports:
   - 3000:3000
  stdin_open: true

volumes:
 db_data:
  driver: local